### PR TITLE
fix bugs

### PR DESCRIPTION
**Pull request by turt2live**
cuz #4

### CODE REVIEW

**Comment by SuperSpyTX** [comment]
ths brok my server, this is shitty fix

u suk

**Comment by turt2live** [comment]
nuu. i dun get errs anemor

**Comment by SuperSpyTX** [comment]
i got except org.turt2live.TimeToLiveException

**Comment by turt2live** [comment]
nu, thats on pr6

**Comment by SuperSpyTX** [comment]
no u

**Comment by turt2live** [comment]
fuq u mine is bttr

**Comment by SuperSpyTX** [comment]
no u

**Comment by davismariotti** [comment]
D:

**Pull request closed without merging**
