### PR TITLE
Fixed LongHugSet to use new LongHashSet public interfaces

### PR DESCRIPTION
**Pull request by netizen539**
This should get plugin catcher working again. Tested it on my server and works for me.

### CODE REVIEW

**Comment by mbax** [comment]
You didn't autocrlf :(

**Comment by SuperSpyTX** [comment]
This is a sad day for @mbax :(

**Comment by netizen539** [comment]
huh? OH snap line endings. =P That's probably why the whole file said it
changed. Sorry about that. =( For future reference .. . what is this
autocrlf you
speak of?

**Comment by netizen539** [comment]
Nvm, got it figured out, will try and fix this.

**Pull request closed without merging**
